[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {  version = "1.0.228", features = ["derive"] }
structopt = "0.3.26"
tokio = {  version = "1.47.1" , features = ["full"] }
toml = "0.9.7"
regex = "1"
